# Generated by Django 4.1.2 on 2022-10-14 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='Название статьи на английском')),
                ('title', models.CharField(max_length=50, verbose_name='Название статьи')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='MarkedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribe_to_post', models.BooleanField(default=False, verbose_name='Подписка на пост')),
                ('time_subscribe_to_post', models.DateTimeField(auto_now_add=True, verbose_name='Дата подписки')),
                ('read_article', models.BooleanField(default=False, verbose_name='Прочитанная статья')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.article', verbose_name='Пост')),
                ('showing_to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Показывать для пользователя')),
            ],
            options={
                'verbose_name': 'Статья для авторизованного пользователя',
                'verbose_name_plural': 'Статьи для авторизованных пользователей',
            },
        ),
        migrations.CreateModel(
            name='CountArticleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(verbose_name='Количество статей автора')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Количество статей пользователя',
                'verbose_name_plural': 'Количество статей пользоватей',
            },
        ),
    ]
