# Generated by Django 4.1.2 on 2022-10-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countarticleuser',
            name='author',
        ),
        migrations.RemoveField(
            model_name='markedarticle',
            name='article',
        ),
        migrations.RemoveField(
            model_name='markedarticle',
            name='showing_to_user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='CountArticleUser',
        ),
        migrations.DeleteModel(
            name='MarkedArticle',
        ),
    ]
